version: "3.8"

volumes:
  postgres_data:
    driver: local

networks:
  skyblog_net:
    name: skyblog_net

services:
  skyblog-db:
    image: postgres:15.1
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: my_user
      POSTGRES_DB: skyblog
      POSTGRES_PASSWORD: root
    networks:
      - skyblog_net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - skyblog_net
    depends_on:
      skyblog-db:
        condition: service_started

  skyblog-api-setup:
    image: skyblog-api
    command: npx prisma db push && npx prisma generate
    restart: "no"
    environment:
      DATABASE_URL: "postgresql://my_user:root@skyblog-db:5432/skyblog?schema=public"
    networks:
      - skyblog_net
    depends_on:
      skyblog-db:
        condition: service_started

  skyblog-api:
    image: skyblog-api
    restart: always
    environment:
      DATABASE_URL: "postgresql://my_user:root@skyblog-db:5432/skyblog?schema=public"
      JWT_SECRET: "fsdfd484f1d6s5f8d1s65fds16"
    ports:
      - 4000:4000
    networks:
      - skyblog_net
    depends_on:
      skyblog-api-setup:
        condition: service_started

  skyblog-front:
    image: skyblog-front
    restart: always
    ports:
      - 3000:3000
    networks:
      - skyblog_net
    depends_on:
      skyblog-api:
        condition: service_started
